@startuml
namespace aliasmethods {
    class "Code"  << (D,  ff7700ff) type of __int__ >> {
        + AsInt() int
    }
    class "Properties"  << (D,  ff7700ff)  >> {
        + Copy() Properties
    }
    class "StringList"  << (D,  ff7700ff)  >> {
        + Add(s string) StringList
    }
}
namespace aliasmethods {
    class "map[string]interface{}" as mapstringinterface << (m,  3cb371ff)  >> {
    }
}
"aliasmethods.mapstringinterface" #.. "aliasmethods.Properties"
namespace aliasmethods {
    class "[]string" as string << (s,  3cb371ff)  >> {
    }
}
"aliasmethods.string" #.. "aliasmethods.StringList"
@enduml
